#!/bin/sh

: "${OUTPUT_DIR:=/var/lib/agent_output}"

export STDOUT="${OUTPUT_DIR}/stdout.txt"
export STDERR="${OUTPUT_DIR}/stderr.txt"

mkdir -p "${OUTPUT_DIR}"

HEAD="


=====================
$(date +%Y%m%d-%H:%M:%S-%Z)

"

echo "${HEAD}" >> "${STDOUT}"
echo "${HEAD}" >> "${STDERR}"

run_ab.sh 1>>"${STDOUT}" 2>>"${STDERR}"

if [ "$DEBUG" == "sh" ] ; then
  sh
fi