#!/bin/sh
# From https://github.com/faisyl/alpine-runit
env > /etc/envvars

/etc/rc.local
rc=$?
if [ $rc -ne 0 ];
then
    echo >&2 "RR failed to start"
    exit $rc
fi

exec /sbin/runsvdir -P /etc/service
